Use unsigned int instead of uint
Improves portability by avoiding the non-standard uint. For example
this fixes building with musl libc:

"../mimetic/codec/other_codecs.h:112:20: error: expected ')' before 'm'
  112 |     MaxLineLen(uint m)
      |               ~    ^~
      |                    )"